// Auto-generiert aus HerculesWS/Hercules db/pre-re/skill_db.conf (Id -> Description).
// Nur zur Anzeige: der Hercules-Anzeigename je Skill (fuer das "(Herc: ...)"-Suffix in der Skill-Liste).

export const HERC_NAMES: Record<string, string> = {
  AC_CHARGEARROW: "Arrow Repel",
  AC_CONCENTRATION: "Improve Concentration",
  AC_DOUBLE: "Double Strafe",
  AC_MAKINGARROW: "Arrow Crafting",
  AC_OWL: "Owl's Eye",
  AC_SHOWER: "Arrow Shower",
  AC_VULTURE: "Vulture's Eye",
  AL_ANGELUS: "Angelus",
  AL_BLESSING: "Blessing",
  AL_CRUCIS: "Signum Crucis",
  AL_CURE: "Cure",
  AL_DECAGI: "Decrease AGI",
  AL_DEMONBANE: "Demon Bane",
  AL_DP: "Divine Protection",
  AL_HEAL: "Heal",
  AL_HOLYLIGHT: "Holy Light",
  AL_HOLYWATER: "Aqua Benedicta",
  AL_INCAGI: "Increase AGI",
  AL_PNEUMA: "Pneuma",
  AL_RUWACH: "Ruwach",
  AL_TELEPORT: "Teleport",
  AL_WARP: "Warp Portal",
  ALL_RESURRECTION: "Resurrection",
  AM_ACIDTERROR: "Acid Terror",
  AM_AXEMASTERY: "Axe Mastery",
  AM_BERSERKPITCHER: "Aid Berserk Potion",
  AM_BIOETHICS: "Bioethics",
  AM_CALLHOMUN: "Call Homunculus",
  AM_CANNIBALIZE: "Summon Flora",
  AM_CP_ARMOR: "Synthetic Armor",
  AM_CP_HELM: "Biochemical Helm",
  AM_CP_SHIELD: "Synthesized Shield",
  AM_CP_WEAPON: "Alchemical Weapon",
  AM_DEMONSTRATION: "Bomb",
  AM_LEARNINGPOTION: "Potion Research",
  AM_PHARMACY: "Prepare Potion",
  AM_POTIONPITCHER: "Aid Potion",
  AM_REST: "Vaporize",
  AM_RESURRECTHOMUN: "Homunculus Resurrection",
  AM_SPHEREMINE: "Summon Marine Sphere",
  AM_TWILIGHT1: "Twilight Alchemy 1",
  AM_TWILIGHT2: "Twilight Alchemy 2",
  AM_TWILIGHT3: "Twilight Alchemy 3",
  AS_CLOAKING: "Cloaking",
  AS_ENCHANTPOISON: "Enchant Poison",
  AS_GRIMTOOTH: "Grimtooth",
  AS_KATAR: "Katar Mastery",
  AS_LEFT: "Lefthand Mastery",
  AS_POISONREACT: "Poison React",
  AS_RIGHT: "Righthand Mastery",
  AS_SONICACCEL: "Sonic Acceleration",
  AS_SONICBLOW: "Sonic Blow",
  AS_SPLASHER: "Venom Splasher",
  AS_VENOMDUST: "Venom Dust",
  AS_VENOMKNIFE: "Throw Venom Knife",
  ASC_BREAKER: "Soul Destroyer",
  ASC_CDP: "Create Deadly Poison",
  ASC_EDP: "Enchant Deadly Poison",
  ASC_KATAR: "Advanced Katar Mastery",
  ASC_METEORASSAULT: "Meteor Assault",
  BA_APPLEIDUN: "Song of Lutie",
  BA_ASSASSINCROSS: "Impressive Riff",
  BA_DISSONANCE: "Unchained Serenade",
  BA_MUSICALLESSON: "Music Lessons",
  BA_MUSICALSTRIKE: "Melody Strike",
  BA_PANGVOICE: "Pang Voice",
  BA_POEMBRAGI: "Magic Strings",
  BA_WHISTLE: "Perfect Tablature",
  BD_ADAPTATION: "Amp",
  BD_DRUMBATTLEFIELD: "Battle Theme",
  BD_ENCORE: "Encore",
  BD_ETERNALCHAOS: "Down Tempo",
  BD_INTOABYSS: "Power Chord",
  BD_LULLABY: "Lullaby",
  BD_RICHMANKIM: "Mental Sensing",
  BD_RINGNIBELUNGEN: "Harmonic Lick",
  BD_ROKISWEIL: "Classical Pluck",
  BD_SIEGFRIED: "Acoustic Rhythm",
  BS_ADRENALINE: "Adrenaline Rush",
  BS_ADRENALINE2: "Advanced Adrenaline Rush",
  BS_AXE: "Smith Axe",
  BS_DAGGER: "Smith Dagger",
  BS_ENCHANTEDSTONE: "Enchanted Stone Craft",
  BS_FINDINGORE: "Ore Discovery",
  BS_GREED: "Greed",
  BS_HAMMERFALL: "Hammer Fall",
  BS_HILTBINDING: "Hilt Binding",
  BS_IRON: "Iron Tempering",
  BS_KNUCKLE: "Smith Knucklebrace",
  BS_MACE: "Smith Mace",
  BS_MAXIMIZE: "Maximize Power",
  BS_ORIDEOCON: "Oridecon Research",
  BS_OVERTHRUST: "Power-Thrust",
  BS_REPAIRWEAPON: "Weapon Repair",
  BS_SKINTEMPER: "Skin Tempering",
  BS_SPEAR: "Smith Spear",
  BS_STEEL: "Steel Tempering",
  BS_SWORD: "Smith Sword",
  BS_TWOHANDSWORD: "Smith Two-handed Sword",
  BS_UNFAIRLYTRICK: "Unfair Trick",
  BS_WEAPONPERFECT: "Weapon Perfection",
  BS_WEAPONRESEARCH: "Weaponry Research",
  CG_ARROWVULCAN: "Vulcan Arrow",
  CG_HERMODE: "Wand of Hermode",
  CG_LONGINGFREEDOM: "Longing for Freedom",
  CG_MARIONETTE: "Marionette Control",
  CG_MOONLIT: "Sheltering Bliss",
  CG_TAROTCARD: "Tarot Card of Fate",
  CH_CHAINCRUSH: "Chain Crush Combo",
  CH_PALMSTRIKE: "Raging Palm Strike",
  CH_SOULCOLLECT: "Zen",
  CH_TIGERFIST: "Glacier Fist",
  CR_ACIDDEMONSTRATION: "Acid Demonstration",
  CR_AUTOGUARD: "Guard",
  CR_CULTIVATION: "Plant Cultivation",
  CR_DEFENDER: "Defending Aura",
  CR_DEVOTION: "Sacrifice",
  CR_FULLPROTECTION: "Full Protection",
  CR_GRANDCROSS: "Grand Cross",
  CR_HOLYCROSS: "Holy Cross",
  CR_PROVIDENCE: "Resistant Souls",
  CR_REFLECTSHIELD: "Shield Reflect",
  CR_SHIELDBOOMERANG: "Shield Boomerang",
  CR_SHIELDCHARGE: "Smite",
  CR_SHRINK: "Shrink",
  CR_SLIMPITCHER: "Aid Condensed Potion",
  CR_SPEARQUICKEN: "Spear Quicken",
  CR_TRUST: "Faith",
  DC_DANCINGLESSON: "Dance Lessons",
  DC_DONTFORGETME: "Slow Grace",
  DC_FORTUNEKISS: "Lady Luck",
  DC_HUMMING: "Focus Ballet",
  DC_SCREAM: "Dazzler",
  DC_SERVICEFORYOU: "Gypsy's Kiss",
  DC_THROWARROW: "Slinging Arrow",
  DC_UGLYDANCE: "Hip Shaker",
  DC_WINKCHARM: "Wink of Charm",
  GS_ADJUSTMENT: "AdJustment",
  GS_BULLSEYE: "Bulls Eye",
  GS_CHAINACTION: "Chain Action",
  GS_CRACKER: "Cracker",
  GS_DESPERADO: "Desperado",
  GS_DISARM: "Disarm",
  GS_DUST: "Dust",
  GS_FLING: "Fling",
  GS_FULLBUSTER: "Full Buster",
  GS_GATLINGFEVER: "Gatling Fever",
  GS_GLITTERING: "Flip the Coin",
  GS_GROUNDDRIFT: "Ground Drift",
  GS_INCREASING: "Increasing Accuracy",
  GS_MADNESSCANCEL: "Madness Canceller",
  GS_MAGICALBULLET: "Magical Bullet",
  GS_PIERCINGSHOT: "Piercing Shot",
  GS_RAPIDSHOWER: "Rapid Shower",
  GS_SINGLEACTION: "Single Action",
  GS_SNAKEEYE: "Snake Eye",
  GS_SPREADATTACK: "Spread Attack",
  GS_TRACKING: "Tracking",
  GS_TRIPLEACTION: "Triple Action",
  HP_ASSUMPTIO: "Assumptio",
  HP_BASILICA: "Basilica",
  HP_MANARECHARGE: "Mana Recharge",
  HP_MEDITATIO: "Meditatio",
  HT_ANKLESNARE: "Ankle Snare",
  HT_BEASTBANE: "Beast Bane",
  HT_BLASTMINE: "Blast Mine",
  HT_BLITZBEAT: "Blitz Beat",
  HT_CLAYMORETRAP: "Claymore Trap",
  HT_DETECTING: "Detect",
  HT_FALCON: "Falconry Mastery",
  HT_FLASHER: "Flasher",
  HT_FREEZINGTRAP: "Freezing Trap",
  HT_LANDMINE: "Land Mine",
  HT_PHANTASMIC: "Phantasmic Arrow",
  HT_POWER: "Beast Strafing",
  HT_REMOVETRAP: "Remove Trap",
  HT_SANDMAN: "Sandman",
  HT_SHOCKWAVE: "Shockwave Trap",
  HT_SKIDTRAP: "Skid Trap",
  HT_SPRINGTRAP: "Spring Trap",
  HT_STEELCROW: "Steel Crow",
  HT_TALKIEBOX: "Talkie Box",
  HW_GANBANTEIN: "Ganbantein",
  HW_GRAVITATION: "Gravitation Field",
  HW_MAGICCRASHER: "Stave Crasher",
  HW_MAGICPOWER: "Mystical Amplification",
  HW_NAPALMVULCAN: "Napalm Vulcan",
  HW_SOULDRAIN: "Soul Drain",
  KN_AUTOCOUNTER: "Counter Attack",
  KN_BOWLINGBASH: "Bowling Bash",
  KN_BRANDISHSPEAR: "Brandish Spear",
  KN_CAVALIERMASTERY: "Cavalier Mastery",
  KN_CHARGEATK: "Charge Attack",
  KN_ONEHAND: "Onehand Quicken",
  KN_PIERCE: "Pierce",
  KN_RIDING: "Peco Peco Riding",
  KN_SPEARBOOMERANG: "Spear Boomerang",
  KN_SPEARMASTERY: "Spear Mastery",
  KN_SPEARSTAB: "Spear Stab",
  KN_TWOHANDQUICKEN: "Twohand Quicken",
  LK_AURABLADE: "Aura Blade",
  LK_BERSERK: "Frenzy",
  LK_CONCENTRATION: "Concentration",
  LK_HEADCRUSH: "Traumatic Blow",
  LK_JOINTBEAT: "Vital Strike",
  LK_PARRYING: "Parrying",
  LK_SPIRALPIERCE: "Spiral Pierce",
  LK_TENSIONRELAX: "Relax",
  MC_CARTDECORATE: "Cart Decoration",
  MC_CARTREVOLUTION: "Cart Revolution",
  MC_CHANGECART: "Change Cart",
  MC_DISCOUNT: "Discount",
  MC_IDENTIFY: "Item Appraisal",
  MC_INCCARRY: "Enlarge Weight Limit",
  MC_LOUD: "Crazy Uproar",
  MC_MAMMONITE: "Mammonite",
  MC_OVERCHARGE: "Overcharge",
  MC_PUSHCART: "Pushcart",
  MC_VENDING: "Vending",
  MG_COLDBOLT: "Cold Bolt",
  MG_ENERGYCOAT: "Energy Coat",
  MG_FIREBALL: "Fire Ball",
  MG_FIREBOLT: "Fire Bolt",
  MG_FIREWALL: "Fire Wall",
  MG_FROSTDIVER: "Frost Diver",
  MG_LIGHTNINGBOLT: "Lightning Bolt",
  MG_NAPALMBEAT: "Napalm Beat",
  MG_SAFETYWALL: "Safety Wall",
  MG_SIGHT: "Sight",
  MG_SOULSTRIKE: "Soul Strike",
  MG_SRECOVERY: "Increase SP Recovery",
  MG_STONECURSE: "Stone Curse",
  MG_THUNDERSTORM: "Thunderstorm",
  MO_ABSORBSPIRITS: "Absorb Spirit Sphere",
  MO_BALKYOUNG: "Ki Explosion",
  MO_BLADESTOP: "Root",
  MO_BODYRELOCATION: "Snap",
  MO_CALLSPIRITS: "Summon Spirit Sphere",
  MO_CHAINCOMBO: "Raging Quadruple Blow",
  MO_COMBOFINISH: "Raging Thrust",
  MO_DODGE: "Dodge",
  MO_EXPLOSIONSPIRITS: "Fury",
  MO_EXTREMITYFIST: "Asura Strike",
  MO_FINGEROFFENSIVE: "Throw Spirit Sphere",
  MO_INVESTIGATE: "Occult Impaction",
  MO_IRONHAND: "Iron Fists",
  MO_KITRANSLATION: "Ki Translation",
  MO_SPIRITSRECOVERY: "Spiritual Cadence",
  MO_STEELBODY: "Mental Strength",
  MO_TRIPLEATTACK: "Raging Trifecta Blow",
  NJ_BAKUENRYU: "Raging Fire Dragon",
  NJ_BUNSINJYUTSU: "Mirror Image",
  NJ_HUUJIN: "Wind Blade",
  NJ_HUUMA: "Throw Huuma Shuriken",
  NJ_HYOUSENSOU: "Spear of Ice",
  NJ_HYOUSYOURAKU: "Ice Meteor",
  NJ_ISSEN: "Final Strike",
  NJ_KAENSIN: "Crimson Fire Formation",
  NJ_KAMAITACHI: "Kamaitachi",
  NJ_KASUMIKIRI: "Vanishing Slash",
  NJ_KIRIKAGE: "Shadow Slash",
  NJ_KOUENKA: "Crimson Fire Petal",
  NJ_KUNAI: "Throw Kunai",
  NJ_NEN: "Soul",
  NJ_NINPOU: "Spirit of the Blade",
  NJ_RAIGEKISAI: "Lightning Strike of Destruction",
  NJ_SHADOWJUMP: "Shadow Leap",
  NJ_SUITON: "Hidden Water",
  NJ_SYURIKEN: "Throw Shuriken",
  NJ_TATAMIGAESHI: "Improvised Defense",
  NJ_TOBIDOUGU: "Shuriken Training",
  NJ_UTSUSEMI: "Cicada Skin Sheeding",
  NJ_ZENYNAGE: "Throw Zeny",
  NV_BASIC: "Basic Skill",
  NV_FIRSTAID: "First Aid",
  NV_TRICKDEAD: "Play Dead",
  PA_GOSPEL: "Battle Chant",
  PA_PRESSURE: "Gloria Domini",
  PA_SACRIFICE: "Martyr's Reckoning",
  PA_SHIELDCHAIN: "Shield Chain",
  PF_DOUBLECASTING: "Double Casting",
  PF_FOGWALL: "Blinding Mist",
  PF_HPCONVERSION: "Indulge",
  PF_MEMORIZE: "Foresight",
  PF_MINDBREAKER: "Mind Breaker",
  PF_SOULBURN: "Soul Siphon",
  PF_SOULCHANGE: "Soul Exhale",
  PF_SPIDERWEB: "Fiber Lock",
  PR_ASPERSIO: "Aspersio",
  PR_BENEDICTIO: "B.S. Sacramenti",
  PR_GLORIA: "Gloria",
  PR_IMPOSITIO: "Impositio Manus",
  PR_KYRIE: "Kyrie Eleison",
  PR_LEXAETERNA: "Lex Aeterna",
  PR_LEXDIVINA: "Lex Divina",
  PR_MACEMASTERY: "Mace Mastery",
  PR_MAGNIFICAT: "Magnificat",
  PR_MAGNUS: "Magnus Exorcismus",
  PR_REDEMPTIO: "Redemptio",
  PR_SANCTUARY: "Sanctuary",
  PR_SLOWPOISON: "Slow Poison",
  PR_STRECOVERY: "Status Recovery",
  PR_SUFFRAGIUM: "Suffragium",
  PR_TURNUNDEAD: "Turn Undead",
  RG_BACKSTAP: "Back Stab",
  RG_CLEANER: "Remover",
  RG_CLOSECONFINE: "Close Confine",
  RG_COMPULSION: "Haggle",
  RG_FLAGGRAFFITI: "Piece",
  RG_GANGSTER: "Slyness",
  RG_GRAFFITI: "Scribble",
  RG_INTIMIDATE: "Snatch",
  RG_PLAGIARISM: "Intimidate",
  RG_RAID: "Sightless Mind",
  RG_SNATCHER: "Gank",
  RG_STEALCOIN: "Mug",
  RG_STRIPARMOR: "Divest Armor",
  RG_STRIPHELM: "Divest Helm",
  RG_STRIPSHIELD: "Divest Shield",
  RG_STRIPWEAPON: "Divest Weapon",
  RG_TUNNELDRIVE: "Stalk",
  SA_ABRACADABRA: "Hocus-pocus",
  SA_ADVANCEDBOOK: "Study",
  SA_AUTOSPELL: "Hindsight",
  SA_CASTCANCEL: "Cast Cancel",
  SA_CREATECON: "Create Elemental Converter",
  SA_DELUGE: "Deluge",
  SA_DISPELL: "Dispell",
  SA_DRAGONOLOGY: "Dragonology",
  SA_ELEMENTFIRE: "Elemental Change Fire",
  SA_ELEMENTGROUND: "Elemental Change Earth",
  SA_ELEMENTWATER: "Elemental Change Water",
  SA_ELEMENTWIND: "Elemental Change Wind",
  SA_FLAMELAUNCHER: "Endow Blaze",
  SA_FREECAST: "Free Cast",
  SA_FROSTWEAPON: "Endow Tsunami",
  SA_LANDPROTECTOR: "Magnetic Earth",
  SA_LIGHTNINGLOADER: "Endow Tornado",
  SA_MAGICROD: "Magic Rod",
  SA_SEISMICWEAPON: "Endow Quake",
  SA_SPELLBREAKER: "Spell Breaker",
  SA_VIOLENTGALE: "Whirlwind",
  SA_VOLCANO: "Volcano",
  SG_DEVIL: "Demon of the Sun Moon and Stars",
  SG_FEEL: "Feeling the Sun Moon and Stars",
  SG_FRIEND: "Friend of the Sun Moon and Stars",
  SG_FUSION: "Union of the Sun Moon and Stars",
  SG_HATE: "Hatred of the Sun Moon and Stars",
  SG_KNOWLEDGE: "Knowledge of the Sun Moon and Stars",
  SG_MOON_ANGER: "Anger of the Moon",
  SG_MOON_BLESS: "Blessing of the Moon",
  SG_MOON_COMFORT: "Comfort of the Moon",
  SG_MOON_WARM: "Warmth of the Moon",
  SG_STAR_ANGER: "Anger of the Stars",
  SG_STAR_BLESS: "Blessing of the Stars",
  SG_STAR_COMFORT: "Comfort of the Stars",
  SG_STAR_WARM: "Warmth of the Stars",
  SG_SUN_ANGER: "Anger of the Sun",
  SG_SUN_BLESS: "Blessing of the Sun",
  SG_SUN_COMFORT: "Comfort of the Sun",
  SG_SUN_WARM: "Warmth of the Sun",
  SL_ALCHEMIST: "Spirit of the Alchemist",
  SL_ASSASIN: "Spirit of the Assasin",
  SL_BARDDANCER: "Spirit of the Artist",
  SL_BLACKSMITH: "Spirit of the Blacksmith",
  SL_CRUSADER: "Spirit of the Crusader",
  SL_HIGH: "Spirit of Rebirth",
  SL_HUNTER: "Spirit of the Hunter",
  SL_KAAHI: "Kaahi",
  SL_KAINA: "Kaina",
  SL_KAITE: "Kaite",
  SL_KAIZEL: "Kaizel",
  SL_KAUPE: "Kaupe",
  SL_KNIGHT: "Spirit of the Knight",
  SL_MONK: "Spirit of the Monk",
  SL_PRIEST: "Spirit of the Priest",
  SL_ROGUE: "Spirit of the Rogue",
  SL_SAGE: "Spirit of the Sage",
  SL_SKA: "Eska",
  SL_SKE: "Eske",
  SL_SMA: "Esma",
  SL_SOULLINKER: "Spirit of the Soul Linker",
  SL_STAR: "Spirit of the Star Gladiator",
  SL_STIN: "Estin",
  SL_STUN: "Estun",
  SL_SUPERNOVICE: "Spirit of the Supernovice",
  SL_SWOO: "Eswoo",
  SL_WIZARD: "Spirit of the Wizard",
  SM_AUTOBERSERK: "Auto Berserk",
  SM_BASH: "Bash",
  SM_ENDURE: "Endure",
  SM_FATALBLOW: "Fatal Blow",
  SM_MAGNUM: "Magnum Break",
  SM_MOVINGRECOVERY: "Moving HP-Recovery",
  SM_PROVOKE: "Provoke",
  SM_RECOVERY: "Increase HP Recovery",
  SM_SWORD: "Sword Mastery",
  SM_TWOHAND: "Two-Handed Sword Mastery",
  SN_FALCONASSAULT: "Falcon Assault",
  SN_SHARPSHOOTING: "Focused Arrow Strike",
  SN_SIGHT: "Falcon Eyes",
  SN_WINDWALK: "Wind Walker",
  ST_CHASEWALK: "Stealth",
  ST_FULLSTRIP: "Divest All",
  ST_PRESERVE: "Preserve",
  ST_REJECTSWORD: "Counter Instinct",
  TF_BACKSLIDING: "Back Slide",
  TF_DETOXIFY: "Detoxify",
  TF_DOUBLE: "Double Attack",
  TF_HIDING: "Hiding",
  TF_MISS: "Improve Dodge",
  TF_PICKSTONE: "Find Stone",
  TF_POISON: "Envenom",
  TF_SPRINKLESAND: "Sand Attack",
  TF_STEAL: "Steal",
  TF_THROWSTONE: "Stone Fling",
  TK_COUNTER: "Counter Kick",
  TK_DODGE: "Tumbling",
  TK_DOWNKICK: "Heel Drop",
  TK_HIGHJUMP: "Taekwon Jump",
  TK_HPTIME: "Peaceful Break",
  TK_JUMPKICK: "Flying Kick",
  TK_MISSION: "Taekwon Mission",
  TK_POWER: "Kihop",
  TK_READYCOUNTER: "Counter Kick Stance",
  TK_READYDOWN: "Heel Drop Stance",
  TK_READYSTORM: "Tornado Stance",
  TK_READYTURN: "Roundhouse Stance",
  TK_RUN: "Running",
  TK_SEVENWIND: "Mild Wind",
  TK_SPTIME: "Happy Break",
  TK_STORMKICK: "Tornado Kick",
  TK_TURNKICK: "Roundhouse Kick",
  WS_CARTBOOST: "Cart Boost",
  WS_CARTTERMINATION: "Cart Termination",
  WS_MELTDOWN: "Shattering Strike",
  WS_OVERTHRUSTMAX: "Maximum Power Thrust",
  WS_WEAPONREFINE: "Upgrade Weapon",
  WZ_EARTHSPIKE: "Earth Spike",
  WZ_ESTIMATION: "Sense",
  WZ_FIREPILLAR: "Fire Pillar",
  WZ_FROSTNOVA: "Frost Nova",
  WZ_HEAVENDRIVE: "Heaven's Drive",
  WZ_ICEWALL: "Ice Wall",
  WZ_JUPITEL: "Jupitel Thunder",
  WZ_METEOR: "Meteor Storm",
  WZ_QUAGMIRE: "Quagmire",
  WZ_SIGHTBLASTER: "Sight Blaster",
  WZ_SIGHTRASHER: "Sightrasher",
  WZ_STORMGUST: "Storm Gust",
  WZ_VERMILION: "Lord of Vermilion",
  WZ_WATERBALL: "Water Ball",
}
